export type ErrorCode =
  | "SECURITY_ERROR"
  | "ACCESS_DENIED"
  | "QUERY_PARSING_ERROR"
  | "TABLE_NOT_FOUND"
  | "COLUMN_NOT_FOUND"
  | "RELATION_NOT_FOUND"
  | "ALIAS_NOT_FOUND"
  | "CONFIGURATION_ERROR"
  | "MUTATION_ERROR";
